In [3]:
import torch

In [8]:
x = torch.tensor([5.5,3])
print(x)

tensor([5.5000, 3.0000])


In [9]:
x = x.new_ones(5,3,dtype=torch.float64)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [12]:
x = torch.randn_like(x,dtype=torch.float)
print(x)

tensor([[ 1.4601, -1.2203, -1.9488],
        [-0.5186,  0.8739, -0.9246],
        [-0.5737,  2.0663, -1.2440],
        [ 0.1094,  2.2181,  1.0346],
        [-1.4740, -1.7017,  0.1810]])


In [15]:
a = torch.ones(5)
b = a.numpy()
print(a,'\n',b)
a += 1
print(a,'\n',b)
b += 1
print(a,'\n',b)

tensor([1., 1., 1., 1., 1.]) 
 [1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2.]) 
 [2. 2. 2. 2. 2.]
tensor([3., 3., 3., 3., 3.]) 
 [3. 3. 3. 3. 3.]


In [16]:

if torch.cuda.is_available():
    device = torch.device("cuda") 
    y = torch.ones_like(x, device=device) 
    x = x.to(device) 
    z = x + y
    print(z)
    print(z.to("cpu", torch.double)) 

tensor([[ 2.4601, -0.2203, -0.9488],
        [ 0.4814,  1.8739,  0.0754],
        [ 0.4263,  3.0663, -0.2440],
        [ 1.1094,  3.2181,  2.0346],
        [-0.4740, -0.7017,  1.1810]], device='cuda:0')
tensor([[ 2.4601, -0.2203, -0.9488],
        [ 0.4814,  1.8739,  0.0754],
        [ 0.4263,  3.0663, -0.2440],
        [ 1.1094,  3.2181,  2.0346],
        [-0.4740, -0.7017,  1.1810]], dtype=torch.float64)


In [1]:
import torch
from torch import nn
torch.cuda.is_available()

True

In [2]:
torch.cuda.device_count()

1

In [3]:
torch.cuda.current_device()

0

In [4]:
torch.cuda.get_device_name(0)

'GeForce 930M'